#!/bin/bash
#
# Pack shared and copy nuspec file to Local Packages
#
# Required env variables: 
#   grid_repository_dir - absolute path to directory of the grid repository
#   shared_repository_dir - absolute path to directory of the shared repository
#
# Required scripts: 
#   nuget-pack
#   clear-shared-cache
#
# Optional scripts: 
#   shared - for pre-building

say() {
	echo "$@" 1>&2 # redirect stdout to stderr
}

die() {
	say "$2"
	exit "$1"
}

function echo_help() {
	echo "Pack nuget shared."
    echo " "
    echo "actions:"
    echo "-h, --help        					          show brief help"
    echo "-s, --set-config       set Grid 3 directory build props to 1.0.0.0"
    echo "-b, --build       					          build solution before packing"
    die 0
}

DEFAULT_PACKAGE_VERSION=1.0.0.0 # In the case that the version of the package cannot be found from the assembly file, this is the default we'll use.
SET_GRID_CONFIG=false
BUILD_BEFORE_PACKING=false

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo_help
      ;;
    -s|--set-config)
      SET_GRID_CONFIG=true
      shift
      ;;
    -b|--build)
      BUILD_BEFORE_PACKING=true
      shift
      ;;
  	-sb|-bs)
      SET_GRID_CONFIG=true
      BUILD_BEFORE_PACKING=true
      shift
      ;;
    *)
	  shift
      continue
      ;;
  esac
done

if $BUILD_BEFORE_PACKING; then
	shared -b || exit 1
fi


echo " 
-- Creating packages --
"
SHARED_PROJ_PATH="${shared_repository_dir}/Source/SensorySoftware.Shared/SensorySoftware.Shared.csproj"
METAFILE_NUSPEC_PATH="${shared_repository_dir}/Source/SensorySoftware.Symbols.MetafileReader.Desktop/SensorySoftware.Symbols.MetafileReader.Desktop.csproj"
SHARED_DESKTOP_PROJ_PATH="${shared_repository_dir}/Source/SensorySoftware.Shared.Desktop/SensorySoftware.Shared.Desktop.csproj"
SHARED_FLUENTUI_PROJ_PATH="${shared_repository_dir}/Source/SensorySoftware.Shared.FluentUI/SensorySoftware.Shared.FluentUI.csproj"

nuget-pack $SHARED_PROJ_PATH $SHARED_DESKTOP_PROJ_PATH $SHARED_FLUENTUI_PROJ_PATH $SHARED_IOS_PROJ_PATH $METAFILE_NUSPEC_PATH

echo " 
-- Removing cached packages --
"
clear-shared-cache

if $SET_GRID_CONFIG; then
	echo "
	-- Setting Directory.Build.Props SharedVersion --
	"
	ASSEMBLY_INFO_DIR="${shared_repository_dir}/Source/SensorySoftware.shared/Properties/AssemblyInfo.cs"
	PACKAGE_VERSION=$(grep -oP 'AssemblyFileVersion\(\"\K([0-9]\.[0-9]\.[0-9]\.[0-9])' "${ASSEMBLY_INFO_DIR}")
 	test "$PACKAGE_VERSION" == "" && PACKAGE_VERSION="${DEFAULT_PACKAGE_VERSION}" && echo "No package version obtained from ${ASSEMBLY_INFO_DIR}"
 	echo "Setting package version to ${PACKAGE_VERSION}"
	
	# sed for the old props format: if it can't find it, it won't change anything
	sed --in-place s_"SharedVersion>1\.[0-1]\.[0-9]\.[0-9][0-9][0-9]"_"SharedVersion>${PACKAGE_VERSION}"_g ${grid_repository_dir}/Source/Directory.Build.props
	
	# sed for the new range props format: if it can't find it, it won't change anything
	sed --in-place s_"SharedVersion>\[1\.[0-1]\.[0-9]\.[0-9][0-9][0-9]"_"SharedVersion>\[${PACKAGE_VERSION}"_g ${grid_repository_dir}/Source/Directory.Build.props
	
  echo "Show SharedVersion now in Directory.Build.props:"
  grep SharedVersion ${grid_repository_dir}/Source/Directory.Build.props
fi

