#!/bin/bash

function update-bash-all(){
	
	local BASH_CORE_FILES=~/.bash/.bash_core
	if [ ! -d $BASH_CORE_FILES ];then
		mkdir $BASH_CORE_FILES
	fi

	local HOST=$hostname

	cp ~/.bashrc ~/.bash/.bash_core/.bashrc.${HOSTNAME}
	cp ~/.bash_profile ~/.bash/.bash_core/.bash_profile.${HOSTNAME}
	cd ~/.bash
	git pull
	git add .
	git commit -m 'Generic update'
	git push
	cd -
	ascii_ok
}

function backup-bashrc-bashprofile(){

	local BASH_CORE_FILES=~/.bash/.bash_core
	if [ ! -d $BASH_CORE_FILES ];then
		mkdir $BASH_CORE_FILES
	fi

	local HOST=$hostname

	cp ~/.bashrc ~/.bash/.bash_core/.bashrc.${HOSTNAME}
	cp ~/.bash_profile ~/.bash/.bash_core/.bash_profile.${HOSTNAME}
}

ds() {
    echo "Disk space for user $HOSTNAME"
    df -h
}


