#! /bin/bash

function update-bloodbraid-jsonlib(){
	cd ~/Documents/data_store/mtgjson
	git pull
	cd -
}

# To account for CON. files in the json library (that Windows 10 won't allow) we'll manually scrape them using curl here.

function update-bloodbraid-jsonlib-full(){
	cd ~/Documents/data_store/mtgjson
	printf "Pulling updates for json library..."
	git pull
	cd json
	printf "Getting list of CON.* files that WIN 10 doesn't like"
	DELETEDLIST=$(git status | grep "deleted" | cut -d : -f 2)
	
	for i in $DELETEDLIST; do
		NEWFILENAME="_$i"
		printf "/---------------------------------\\"
		printf "\n" 
		printf "New file to be created: $i\n"
		printf "\\---------------------------------/\n"
		touch $NEWFILENAME
		curl -o "$NEWFILENAME" "https://raw.githubusercontent.com/mtgjson/mtgjson/master/json/$i"
	done

	cd ~/
}
