#!/bin/sh

if [[ $1 -eq "--release" ]]; then
	msbuild32 "C:\Dev\eyegaze\Source\SensorySoftware.EyeGaze.sln" /p:Configuration=Release
fi

msbuild32 "C:\Dev\eyegaze\Source\SensorySoftware.EyeGaze.sln" -p:Configuration=Debug
