#!/bin/bash
BIN_COPY_PATH='/C/Dev/tools/scripts/bash/scripts/'
SOURCEABLE_COPY_PATH='/C/Dev/tools/scripts/bash/sourceable/'
cp "$BIN_COPY_PATH/git-log-release" ~/.bash/global/scripts 
cp "${BIN_COPY_PATH}/git-unique-log" ~/.bash/global/scripts/glogu 
sed --in-place s_"git-unique-log"_"glogu"_g ~/.bash/global/scripts/glogu 
cp "${BIN_COPY_PATH}/git-unique-checkout" ~/.bash/global/scripts/gchu 
sed --in-place s_"git-unique-checkout"_"gchu"_g ~/.bash/global/scripts/gchu 
cp "${BIN_COPY_PATH}/git-unique-rebase" ~/.bash/global/scripts/griu 
sed --in-place s_"git-unique-rebase"_"griu"_g ~/.bash/global/scripts/griu 
cp "$BIN_COPY_PATH/nuget-pack" ~/.bash/global/scripts 
cp "$BIN_COPY_PATH/msbuild32" ~/.bash/global/scripts 

cp "/C/Dev/tools/scripts/bash/scripts/clear-package-cache" ~/.bash/BAN-WORK-TOP/scripts/application 

cp "/C/Dev/tools/scripts/bash/scripts/pack-eyegaze" ~/.bash/BAN-WORK-TOP/scripts/application 
cp "$BIN_COPY_PATH/pack-shared"  ~/.bash/BAN-WORK-TOP/scripts/application

cp "$BIN_COPY_PATH/shared" ~/.bash/BAN-WORK-TOP/scripts/application/build 
cp "$BIN_COPY_PATH/grid" ~/.bash/BAN-WORK-TOP/scripts/application/build 
cp "$BIN_COPY_PATH/eyegaze" ~/.bash/BAN-WORK-TOP/scripts/application/build 