#!/bin/bash
BIN_COPY_PATH='C:\Dev\tools\scripts\bash\scripts\'
SOURCEABLE_COPY_PATH='C:\Dev\tools\scripts\bash\sourceable\'
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\global\scripts\git-log-release' 
cp "${BIN_COPY_PATH}\git-unique-log" 'C:\Users\Bernie\.bash\global\scripts\glogu' 
cp "${BIN_COPY_PATH}\git-unique-checkout" 'C:\Users\Bernie\.bash\global\scripts\gchu' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\global\scripts\nuget-pack' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\global\scripts\msbuild32' 

cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\clear-shared-cache' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\clear-eyegaze-cache' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\pack-eyegaze' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\pack-shared' 

cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\build\shared' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\build\grid' 
cp $BIN_COPY_PATH 'C:\Users\Bernie\.bash\BAN-WORK-TOP\scripts\application\build\eyegaze' 