#!/bin/bash
BIN_COPY_PATH='C:\Dev\tools\scripts\bash\scripts\'
SOURCEABLE_COPY_PATH='C:\Dev\tools\scripts\bash\sourceable\'
cp '~\.bash\global\scripts\git-log-release' $BIN_COPY_PATH
cp '~\.bash\global\scripts\glogu' "${BIN_COPY_PATH}\git-unique-log"
sed --in-place s_"glogu"_"git-unique-log"_g "${BIN_COPY_PATH}\git-unique-log"
cp '~\.bash\global\scripts\gchu' "${BIN_COPY_PATH}\git-unique-checkout"
sed --in-place s_"gchu"_"git-unique-checkout"_g "${BIN_COPY_PATH}\git-unique-checkout"
cp '~\.bash\global\scripts\griu' "${BIN_COPY_PATH}\git-unique-rebase"
sed --in-place s_"griu"_"git-unique-rebase"_g "${BIN_COPY_PATH}\git-unique-rebase"
cp '~\.bash\global\scripts\nuget-pack' $BIN_COPY_PATH
cp '~\.bash\global\scripts\msbuild32' $BIN_COPY_PATH

cp '~\.bash\BAN-WORK-TOP\scripts\application\clear-shared-cache' $BIN_COPY_PATH
cp '~\.bash\BAN-WORK-TOP\scripts\application\clear-eyegaze-cache' $BIN_COPY_PATH
cp '~\.bash\BAN-WORK-TOP\scripts\application\pack-eyegaze' $BIN_COPY_PATH
cp '~\.bash\BAN-WORK-TOP\scripts\application\pack-shared' $BIN_COPY_PATH

cp '~\.bash\BAN-WORK-TOP\scripts\application\build\shared' $BIN_COPY_PATH
cp '~\.bash\BAN-WORK-TOP\scripts\application\build\grid' $BIN_COPY_PATH
cp '~\.bash\BAN-WORK-TOP\scripts\application\build\eyegaze' $BIN_COPY_PATH

#cp '~\.bash\BAN-WORK-TOP\sourceable\env' $SOURCEABLE_COPY_PATH
#cp '~\.bash\BAN-WORK-TOP\sourceable\aliases' $SOURCEABLE_COPY_PATHgs
