#!/bin/bash
#
# Script to tag the next version of a release
#


function say() {
  echo "$@" >&2
}

function die() {
  test -z "$2" || say "$2"
  exit "$1"
}

function echo_help() {
  echo "Tag release"
  echo ""
    echo " "
    echo "actions:"
    echo "-h, --help        show brief help"
    die 0
}

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo_help
      ;;
    -p|--pretty)
    PRETTY=true;
    shift
      ;;
    *)
    shift
      continue
      ;;
  esac
done

PREVIOUS_TAG=$(git describe --tags --abbrev=0)
echo "==============================================" 
echo "Tagging util for Grid and Content repositories"
echo "The previous tag is $PREVIOUS_TAG" 
echo "===============================================" 
echo "" 

TAG_STRING=$(echo $PREVIOUS_TAG | tr "." "\n" )
TAG_ARRAY=($TAG_STRING)
TAG_ARRAY_LENGTH=${#TAG_ARRAY[@]}

# Final item is patch version and second to last is minor version
let "PATCH_INDEX=$TAG_ARRAY_LENGTH - 1"
let "MINOR_VERSION_INDEX=$TAG_ARRAY_LENGTH - 2"

# Assumes tag has the form Grid_3.0.MINOR_VERSION.BUILD_VERSION
PATCH_VERSION=${TAG_ARRAY[$PATCH_INDEX]}
MINOR_VERSION=${TAG_ARRAY[$MINOR_VERSION_INDEX]}

let "PATCH_VERSION_INCREASE=$PATCH_VERSION + 1"
let "MINOR_VERSION_INCREASE=$MINOR_VERSION + 1"

# Construct a new tag for a minor version increase
MINOR_VERSION_TAG_ARRAY=(${TAG_ARRAY[*]})
MINOR_VERSION_TAG_ARRAY[$MINOR_VERSION_INDEX]=$MINOR_VERSION_INCREASE
MINOR_VERSION_TAG_ARRAY[$PATCH_INDEX]=0
TAG_MINOR_VERSION_INCREASE=$( IFS=$'.'; echo "${MINOR_VERSION_TAG_ARRAY[*]}" )

# Construct a new tag for a patch increase
PATCH_VERSION_TAG_ARRAY=(${TAG_ARRAY[*]})
PATCH_VERSION_TAG_ARRAY[$PATCH_INDEX]=$PATCH_VERSION_INCREASE
TAG_PATCH_INCREASE=$( IFS=$'.'; echo "${PATCH_VERSION_TAG_ARRAY[*]}" )

echo "Do you wish to create a tag that increases:"
echo "  1. The minor version from $MINOR_VERSION to $MINOR_VERSION_INCREASE -> $TAG_MINOR_VERSION_INCREASE"
echo "  2. The patch version from $PATCH_VERSION to $PATCH_VERSION_INCREASE -> $TAG_PATCH_INCREASE"
read SELECTED_NUMBER
if [ $SELECTED_NUMBER -eq 1 ]; then
  echo "Incrementing the minor version. Creating new tag called $TAG_MINOR_VERSION_INCREASE which follow $PREVIOUS_TAG."
  git tag $TAG_MINOR_VERSION_INCREASE
elif [ $SELECTED_NUMBER -eq 2 ]; then
  echo "Incrementing the patch version. Creating new tag called $TAG_PATCH_INCREASE which follow $PREVIOUS_TAG."
  git tag $TAG_PATCH_INCREASE
else
  echo "$SELECTED_NUMBER not 1 or 2. Aborting..."
fi