#!/bin/sh

UNIQUE_ID="$1"

MATCHING_BRANCH="$(git branch | grep ${UNIQUE_ID})"

if [ "$(git branch | grep -o ${UNIQUE_ID} | wc -l)" != 1 ]; then
	echo "More than one matching branch:"
	echo ${MATCHING_BRANCH}
	echo "Cannot checkout. Exiting"
	exit
fi

git checkout $MATCHING_BRANCH


