#!/bin/sh
#
# Pack shared and copy nuspec file to Local Packages
#

say() {
	echo "$@" 1>&2 #redirect stdout to stderr
}

die() {
	say "$2"
	exit "$1"
}

# read  -p "Enter your package version number (i.e. 1.0.0.0): " PACKAGE_VERSION

# echo " 
# -- Change grid shared version --
# "

# vim "C:\Dev\shared\Source\SensorySoftware.shared\Properties\AssemblyInfo.cs" || die 2 "file or directory doesn't exist"

# PACKAGE_VERSION=$(grep -oP 'AssemblyFileVersion\(\"\K([0-9]\.[0-9]\.[0-9]\.[0-9])' "C:\Dev\shared\Source\SensorySoftware.shared\Properties\AssemblyInfo.cs")
# echo "Your package version is {$PACKAGE_VERSION}"

# echo " 
# -- Change grid shared.desktop version --
# "

# vim "C:\Dev\shared\Source\SensorySoftware.shared.Desktop\Properties\AssemblyInfo.cs" || die 2 "file or directory doesn't exist"

# echo "
# -- Package version : $PACKAGE_VERSION
# "

# echo " 
# -- Building shared --
# "
# build-shared || die 2 "FAILURE: Building shared failed"


echo " 
-- Creating packages --
"
SHARED_PROJ_PATH="C:\Dev\shared\Source\SensorySoftware.Shared\SensorySoftware.Shared.csproj"
SHARED_DESKTOP_PROJ_PATH="C:\Dev\shared\Source\SensorySoftware.Shared.Desktop\SensorySoftware.Shared.Desktop.csproj"
SHARED_FLUENTUI_PROJ_PATH="C:\Dev\shared\Source\SensorySoftware.Shared.FluentUI\SensorySoftware.Shared.FluentUI.csproj"

nuget-pack $SHARED_PROJ_PATH $SHARED_DESKTOP_PROJ_PATH $SHARED_FLUENTUI_PROJ_PATH $SHARED_IOS_PROJ_PATH

echo " 
-- Removing cached packages --
"
clear-shared-cache


# echo " 
# -- Change grid shared version number to $PACKAGE_VERSION --
# "
# read  -n 1 -p "Press any key to enter Vim and change version number"
# vim '/c/dev/grid/source/directory.build.props' || die 2 "directory doesn't exist"