#!/bin/bash

function say() {
	echo "$@" >&2
}

function title() {
  echo ""
  echo "<--- $1 --->" 
}

function die() {
	test -z "$2" || say "$2"
	exit "$1"
}

title "Restoring solution packages"
nuget restore "${grid_repository_dir}/Source/SensorySoftware.Grid3.sln"  || die 1 "== package restore failed =="

title "Building solution"
msbuild32 "${grid_repository_dir}/Source/SensorySoftware.Grid3.sln" -p:Configuration=Debug -p:Platform="x86" -verbosity:q -consoleloggerparameters:ErrorsOnly || die 1 "== build failed =="