#!/bin/bash
# 
# grid branch tester
#
# Fetches
# Checks out a branch in git based on a unique identifier.
# Cleans
# Restores packages using MSBuild with the -t:restore flag as nuget restore doesn't appear to work for Grid.
# Builds in debug 
# Runs the executable


function say() {
	echo "$@" >&2
}

function title() {
  echo ""
  echo "<--- $1 --->" 
}

function die() {
	test -z "$2" || say "$2"
	exit "$1"
}

function echo_help() {
	echo "Branch tester git."
	echo "First argument should be your unique identifier for the branch in question."
    echo " "
    echo "$ test-branch identifier [actions]"
    echo " "
    echo "actions:"
    echo "-h, --help        show brief help"
    echo "-a, --all         select all branches (including remotes)"
    echo "-r, --remotes     select remote branches"
    die 0
}

UNIQUE_ID="$1"
test -z "$UNIQUE_ID" && echo_help

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo_help
      ;;
    -a|--all)
      GIT_BRANCH_ACTIONS=$GIT_BRANCH_ACTIONS" --all"
      shift
      ;;
  	-r|--remotes)
      GIT_BRANCH_ACTIONS=$GIT_BRANCH_ACTIONS" --remotes"
      shift
      ;;
    *)
	  shift
      continue
      ;;
  esac
done
echo "Using unique ID of $UNIQUE_ID and Git branch actions of $GIT_BRANCH_ACTIONS"

title "FETCHING"
git fetch || die 1 "== git fetch failed =="

title "CHECKING OUT"
gchu $UNIQUE_ID $GIT_BRANCH_ACTIONS || die 1 "== git checkout failed =="

title "CLEANING GIT"
git clean -fxd -e "*.vs" -e "*.vscode" || die 1 "== git clean failed =="

title "RESTORING PACKAGES"
msbuild32 "${grid_repository_dir}/Source/SensorySoftware.Grid3.sln" -t:restore -p:Platform="x86" -verbosity:q -consoleloggerparameters:ErrorsOnly  || die 1 "== package restore failed =="

title "BUILDING GRID"
msbuild32 "${grid_repository_dir}/Source/SensorySoftware.Grid3.sln" -p:Configuration=Debug -p:Platform="x86" -verbosity:q -consoleloggerparameters:ErrorsOnly || die 1 "== build failed =="

title "STARTING GRID"
grid-debug