#!/bin/bash

update-all(){
	read -p "Are you sure you want a generic update of everything? (Y|y)"
	if [[ $REPLY =~ [yY] ]]; 
	then
		update-magic
		update-sublime
		update-writings
		update-javascript-playground
		update-python
	fi
}


update-magic() {
	generic-update 'C:/Users/BAN/AppData/Local/Cockatrice/Cockatrice/decks'
}	

update-sublime() {
	generic-update 'C:/Users/BAN/AppData/Roaming/Sublime Text 3/Packages/User/'
}

update-writings() {
	generic-update  'C:/Users/BAN/Documents/Writings/'
}

update-python() {
	generic-update  'C:/Users/BAN/Documents/Python/'
}

update-javascript-playground() {
	generic-update  'C:/Users/BAN/Documents/JavaScript/'
}

update-shopper-ticker() {
	generic-update  'C:/Users/BAN/Dev/ShopperTicker'
}