#!/bin/sh

function build-eyegaze-release(){
	msbuild32 "C:\Dev\eyegaze\Source\SensorySoftware.EyeGaze.sln" -p:Configuration=Release
}

function build-grid-release(){
	msbuild32 "C:\Dev\grid\Source\SensorySoftware.Grid3.sln" -p:Configuration=Release -p:Platform="x86"
}

function build-eyegaze(){
	msbuild32 "C:\Dev\eyegaze\Source\SensorySoftware.EyeGaze.sln" -p:Configuration=Debug 
}

function build-shared(){
	msbuild32 "C:\Dev\shared\Source\SensorySoftware.Shared.All.sln" -p:Configuration=Debug 
}

function build-grid(){
	msbuild32 "C:\Dev\grid\Source\SensorySoftware.Grid3.sln" -p:Configuration=Debug -p:Platform="x86"
}

function build-grid-all(){
	clear-eyegaze-cache
	msbuild32 "C:\Dev\grid\Source\SensorySoftware.Grid3.sln" -p:Configuration=Debug -p:Platform="x86"
}
