#!/bin/bash

BALL_ONE_PROBABILITY=0.15
BALL_TWO_PROBABILITY=0.35
BALL_THREE_PROBABILITY=0.5

SAMPLES=20
BALL_ONE_COUNT=0;
BALL_TWO_COUNT=0;
BALL_THREE_COUNT=0;

for (( i=1; i<=$SAMPLES; i++ ))
do
	RAND=$(( $RANDOM % 1000 + 1 ))
	echo $(( 1*3 ))
	echo $(( $RAND*$BALL_ONE_PROBABLITY ))

done
