#!/bin/bash

alias cd-grid="cd ${grid_repository_dir}/Source"
alias cd-resources="cd ~/dev/gridresources"
alias cd-inventory="cd ~/dev/published-inventory"
alias cd-text="cd ~/dev/text"
alias cd-speech="cd ~/dev/speech"
alias cd-symbols="cd ~/dev/symbols"
alias cd-eriskay="cd ~/dev/eriskay"
alias cd-looklab="cd ~/dev/looklab"
alias cd-eyegaze="cd ${eyegaze_repository_dir}"
alias cd-shared="cd ${shared_repository_dir}"
alias cd-dev="cd ~/dev"
alias cd-web="cd ${web_repository_dir}"
alias cd-javascript="cd ${smartbox_js_repository_dir}"
alias cd-activate="cd ${web_repository_dir}/activate"
alias cd-tools="cd ~/dev/tools"
alias cd-sublime='cd ~/appdata/roaming/sublime\ text\ 3/packages/user'

#nuget
alias teamcity-package-list="nuget list -source https://teamcity.thinksmartbox.com/httpAuth/app/nuget/v1/FeedService.svc -AllVersions -Prerelease"
alias nuget-restore="nuget restore -nocache"

# logfile analyser
alias lfa="${logfile_analyser_exe}"

# Nuget clear caches
alias clear-shared-cache="clear-package-cache 'sensorysoftware.shared' 'sensorysoftware.shared.desktop' 'sensorysoftware.shared.iOS'  'sensorysoftware.symbols.metafilereader.desktop' 'sensorysoftware.shared.fluentui'"
alias clear-speech-cache="clear-package-cache 'sensorysoftware.speechlib'"
alias clear-text-cache="clear-package-cache 'sensorysoftware.text' 'sensorysoftware.text.desktop'"
alias clear-eyegaze-cache="clear-package-cache 'sensorysoftware.eyegaze' 'sensorysoftware.eyegaze.desktop'"

function pack-shared-local() {
    echo "Packing shared projects and placing the output nupkgs in the local store at ${local_package_store}"
    pwsh -NoProfile -Command "& \"$HOME/.bash/global/scripts/nuget-pack-local.ps1\" -Projects @(
        \"$HOME/dev/shared/Source/SensorySoftware.Shared/SensorySoftware.Shared.csproj\",
        \"$HOME/dev/shared/Source/SensorySoftware.Symbols.MetafileReader.iOS/SensorySoftware.Symbols.MetafileReader.iOS.csproj\",
        \"$HOME/dev/shared/Source/SensorySoftware.Shared.iOS/SensorySoftware.Shared.iOS.csproj\"
    ) -LocalPackageCache \"$HOME/dev/Packages\" -BuildPropsPath \"$HOME/dev/Grid/Source/Directory.Build.Props\" -VersionElement \"SharedVersion\""
}

# function pack-eyegaze-local() {
#     pwsh ~/.bash/global/scripts/nuget-pack-local.ps1 \
#         -Projects @('~/dev/eyegaze/Source/SensorySoftware.EyeGaze/SensorySoftware.EyeGaze.csproj', '~/dev/eyegaze/Source/SensorySoftware.EyeGaze.Desktop/SensorySoftware.EyeGaze.Desktop.csproj') \
#         -LocalPackageCache '~/dev/Packages' \
#         -BuildPropsPath '~/dev/Grid/Source/Directory.Build.Props' \
#         -VersionElement 'EyeGazeVersion'
# }