#!/bin/bash

update-all(){
	read -p "Are you sure you want a generic update of everything? (Y|y)"
	if [[ $REPLY =~ [yY] ]]; 
	then
		update-sublime
		update-writings
		update-javascript-playground
	fi
}

update-sublime() {
	generic-update "/C/Users/bema/AppData/Roaming/Sublime\ Text\ 3/Packages/User/"
}

update-writings() {
	generic-update '/C/Users/bema/Documents/Writings/'
}

update-javascript-playground() {
	generic-update '/C/Users/bema/Documents/JavaScript/'
}

epro-update() {
	EPRO_WORKING_DIR=/C/Dev/Epro
	CURRENT_WORKING_DIR=$(pwd)
	if [ "$CURRENT_WORKING_DIR" != "$EPRO_WORKING_DIR" ];
	then
		echo 'Changing directories...'; cd '/C/Dev/Epro' 
	fi

	BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
	echo "Current branch: $BRANCH"
	if [ "$BRANCH" != "master" ];
	then
		echo 'Checking out master...'; git Checkingckout master
	fi

	IS_UP_TO_DATE=$(git status | grep "Your branch is up-to-date with 'origin/master'.")

	if [ -z "$IS_UP_TO_DATE" ];
	then
		git pull
	else
		echo "Your branch is up-to-date with 'origin/master'."
	fi

	if [ "$BRANCH" != "master" ];
	then
		echo 'Checking out previous branch...'; git checkout -
	fi

	if [ "$CURRENT_WORKING_DIR" != "$EPRO_WORKING_DIR" ];
	then
		echo 'Returning to previous directory...'; cd -
	fi
	return
}
