#!/bin/bash
update-magic() {
	generic-update '~/AppData/Local/Cockatrice/Cockatrice/decks'
}

update-sublime() {
	generic-update '/C/Users/bema/AppData/Roaming/Sublime\ Text\ 3/Packages/User/'
}

update-writings() {
	generic-update '~/Documents/Writings/'
}

update-python() {
	generic-update '~/Documents/Python/'
}
