#!/bin/bash

#shopt -s expand_aliases

alias cd-grid="cd ${grid_repository_dir}/Source"
alias cd-resources="cd /c/dev/gridresources"
alias cd-inventory="cd /c/dev/published-inventory"
alias cd-text="cd /c/dev/text"
alias cd-speech="cd /c/dev/speech"
alias cd-symbols="cd /c/dev/symbols"
alias cd-eriskay="cd /c/dev/eriskay"
alias cd-looklab="cd /c/dev/looklab"
alias cd-eyegaze="cd ${eyegaze_repository_dir}"
alias cd-shared="cd ${shared_repository_dir}"
alias cd-dev="cd /c/dev"
alias cd-web="cd ${web_repository_dir}"
alias cd-javascript="cd ${smartbox_js_repository_dir}"
alias cd-activate="cd ${web_repository_dir}/activate"
alias cd-tools="cd /c/dev/tools"
alias cd-sublime='cd ~/appdata/roaming/sublime\ text\ 3/packages/user'

alias vs-grid='start ${grid_repository_dir}/Source/SensorySoftware.Grid3.sln'
alias vs-shared='start ${shared_repository_dir}/Source/SensorySoftware.Shared.All.sln'
alias vs-activate='start ${web_repository_dir}/activate/Activate.sln'
alias vs-eyegaze='start ${eyegaze_repository_dir}/Source/SensorySoftware.EyeGaze.sln'
alias vs-crashreporter='start ${web_repository_dir}/CrashReporter/src/SensorySoftware.CrashReporter.Site.sln'

# nuget
alias teamcity-package-list="nuget list -source https://teamcity.thinksmartbox.com/httpAuth/app/nuget/v1/FeedService.svc -AllVersions -Prerelease"
alias nuget-restore="nuget restore -nocache"

# logfile analyser
alias lfa="${logfile_analyser_exe}"

# Nuget clear caches
alias clear-shared-cache="clear-package-cache 'sensorysoftware.shared' 'sensorysoftware.shared.desktop' 'sensorysoftware.shared.iOS'  'sensorysoftware.symbols.metafilereader.desktop' 'sensorysoftware.shared.fluentui'"
alias clear-speech-cache="clear-package-cache 'sensorysoftware.speechlib'"
alias clear-text-cache="clear-package-cache 'sensorysoftware.text' 'sensorysoftware.text.desktop'"
alias clear-eyegaze-cache="clear-package-cache 'sensorysoftware.eyegaze' 'sensorysoftware.eyegaze.desktop'"


function pack-shared-local() {
    powershell "~/.bash/global/scripts/nuget-pack-local.ps1 \
        -Projects @('C:/Dev/shared/Source/SensorySoftware.Shared/SensorySoftware.Shared.csproj','C:/Dev/shared/Source/SensorySoftware.Symbols.MetafileReader.Desktop/SensorySoftware.Symbols.MetafileReader.Desktop.csproj','C:/Dev/shared/Source/SensorySoftware.Shared.Desktop/SensorySoftware.Shared.Desktop.csproj','C:/Dev/shared/Source/SensorySoftware.Shared.FluentUI/SensorySoftware.Shared.FluentUI.csproj','C:/Dev/shared/Source/SensorySoftware.Shared.HardwareLicensingServiceClient/SensorySoftware.Shared.HardwareLicensingServiceClient.csproj') \
        -LocalPackageCache 'C:/Dev/Packages' \
        -BuildPropsPath 'C:/Dev/Grid/Source/Directory.Build.Props' \
        -VersionElement 'SharedVersion'"
}

function pack-eyegaze-local() {
    powershell "~/.bash/global/scripts/nuget-pack-local.ps1 \
        -Projects @('C:/Dev/eyegaze/Source/SensorySoftware.EyeGaze/SensorySoftware.EyeGaze.csproj', 'C:/Dev/eyegaze/Source/SensorySoftware.EyeGaze.Desktop/SensorySoftware.EyeGaze.Desktop.csproj') \
        -LocalPackageCache 'C:/Dev/Packages' \
        -BuildPropsPath 'C:/Dev/Grid/Source/Directory.Build.Props' \
        -VersionElement 'EyeGazeVersion'"
}