#!/bin/bash

BACKUP_DIR=~/.bash/backup
if [ ! -d $BACKUP_DIR ];then
	mkdir $BACKUP_DIR
fi

test -f ~/.bashrc && cp ~/.bashrc "${BACKUP_DIR}/.bashrc.${HOSTNAME}"
test -f ~/.bash_profile && cp ~/.bash_profile "${BACKUP_DIR}/.bash_profile.${HOSTNAME}"
test -f ~/.gitconfig && cp ~/.gitconfig "${BACKUP_DIR}/.gitconfig.${HOSTNAME}"