#!/bin/bash
# 
# pattern based git checkout tool
#
# Checks out a branch based on a provided regex.
# If more than one match is found, the tool provides a list of options that may be selected.
#
# By default the script only searches local branches. However it can also search remotes by 
# providing the all or remotes action.
#
# No external dependencies (env variables or scripts)

NC='\033[0m'              # Text Reset
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
BRed='\033[1;31m'         # Red
UYellow='\033[4;33m'      # Yellow
UWhite='\033[4;37m'       # White

function say() {
	echo -e "$@" >&2
}

function die() {
	test -z "$2" || say "$2"
	exit "$1"
}

function fetchForRemotes() {
      echo -e "$1 selected as checkout candidates, performing a git fetch to ensure branch list is up-to-date."
      git fetch
}

function print_help() {
  echo -e "${UWhite}Checkout a branch based on an identifier.${NC}"
  echo -e "First argument should be your string pattern for the branch in question. Supports grep operations."
    echo -e " "
    echo "\$gchu identifier [actions]"
    echo -e " "
    echo -e "actions:"
    echo -e "-h, --help        ${Yellow}show brief help${NC}"
    echo -e "-r, --remotes     ${Yellow}select from just remote branches (will fetch first)${NC}"
    echo -e "-a, --all         ${Yellow}select from local and remote branches (will fetch first)${NC}"
    echo -e "-t, --track       ${Yellow}track selected branch${NC}"
    echo -e "-g, --tags        ${Yellow}tag to checkout${NC}"
    die 0
}

PATTERN="$1"
test -z $PATTERN && print_help
GIT_BRANCH_ACTIONS="--list"
GIT_CHECKOUT_ACTIONS=""
GIT_REF="branch"
RAINBOW_OUTPUT=false;

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      print_help
      ;;
    -a|--all)
      fetchForRemotes "All branches"
      GIT_BRANCH_ACTIONS="${GIT_BRANCH_ACTIONS} --all"
      shift
      ;;
  	-r|--remotes)
      fetchForRemotes "Remote branches"
      GIT_BRANCH_ACTIONS="${GIT_BRANCH_ACTIONS} --remotes"
      shift
      ;;
  	-t|--track)
      GIT_CHECKOUT_ACTIONS=" --track"
      shift
      ;;
    -b|--rainbow)
      RAINBOW_OUTPUT=true;
      shift
      ;;
    -g|--tags)
      fetchForRemotes "Tags"
      GIT_REF="tag"
      shift
      ;;
    -tr|-rt)
      fetchForRemotes "Remote branches"
      GIT_BRANCH_ACTIONS="${GIT_BRANCH_ACTIONS} --remotes"
      GIT_CHECKOUT_ACTIONS=" --track"
      shift
      ;;
    *)
	  shift
      continue
      ;;
  esac
done

MATCHING_BRANCH=$(git $GIT_REF $GIT_BRANCH_ACTIONS | grep -i $PATTERN | sed -E 's/\* (\(HEAD detached at )?//g' )
BRANCHES=($MATCHING_BRANCH)
MATCHCOUNT="${#BRANCHES[@]}"
echo "$MATCHCOUNT"

test $MATCHCOUNT -eq 0 && die 1 "${Red}No matching ${GIT_REF} in the repository ${NC}\"$(basename `git rev-parse --show-toplevel`)\"${Red}  ${NC}\"${PATTERN}\"${Red} Exiting...${NC}"

if (($MATCHCOUNT > 1)); then
	echo -e "${UYellow}More than one match. Select the one you want. E.g. type \"1\" to checkout the first item in the list:${NC}"
	echo ""
	let i=1
  let MAX_LENGTH=0;

  for BRANCH in ${BRANCHES[@]}; do
    BRANCH_LENGTH=$(expr length $BRANCH)
    if (( BRANCH_LENGTH > MAX_LENGTH )); then
      MAX_LENGTH=$BRANCH_LENGTH
    fi
  done
	for BRANCH in ${BRANCHES[@]}; do
    if $RAINBOW_OUTPUT; then
      let OPTION=$((i++))
      echo -e "\e[3$(( $RANDOM * 6 / 32767 + 1 ))m$(printf %6s $OPTION) => $(prinf %${MAX_LENGTH}s $BRANCH)"
    else
      let OPTION=$((i++))
      OPTION_COLOUR="${IBlack}${On_Yellow}"
      if (( $(( $OPTION % 2 )) == 0 )); then OPTION_COLOUR="${Yellow}"; fi
      echo -e "${OPTION_COLOUR}$(printf %6s $OPTION) => $BRANCH${NC}"
    fi
	done
	echo ""
	re='^[0-9]+$'
	read SELECTED_NUMBER
	echo -e "Value read in: \"$SELECTED_NUMBER\""
	if ! [[ $SELECTED_NUMBER =~ $re ]]; then
		die 1 "${BRed}Not a valid option. Exiting...${NC}"
	fi
  if [[ $SELECTED_NUMBER < 1 || $SELECTED_NUMBER > $MATCHCOUNT ]]; then # 
      die 1 "\"$SELECTED_NUMBER\" ${Red}is of bounds. exiting...${NC}"
  fi
	MATCHING_BRANCH=${BRANCHES[$((--SELECTED_NUMBER))]}
	echo -e "${Green}The select ${GIT_REF} is:${NC} \"$MATCHING_BRANCH\""
fi

git checkout$GIT_CHECKOUT_ACTIONS $MATCHING_BRANCH