#!/bin/bash
# 
# pattern based git checkout tool
#
# Checks out a branch based on a provided regex.
# If more than one match is found, the tool provides a list of options that may be selected.
#
# By default the script only searches local branches. However it can also search remotes by 
# providing the all or remotes action.
#
# Depends on formatBranches script

NC='\033[0m'              # Text Reset
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
UWhite='\033[4;37m'
Black='\033[0;30m'

function say() {
	echo -e "$@" >&2
}

function title() {
  echo -e "${Green}>> $@"${NC} >&2
  echo ""
}

function die() {
	test -z "$2" || say "$2"
	exit "$1"
}

function fetchForRemotes() {
      echo -e "$1 selected as checkout candidates, performing a git fetch to ensure branch list is up-to-date."
      git fetch
}

function print_help() {
  echo -e "${UWhite}Checkout a branch based on an identifier.${NC}"
  echo -e "First argument should be your string pattern for the branch in question. Supports grep operations."
    echo -e " "
    echo "\$gchu identifier [actions]"
    echo -e " "
    echo -e "actions:"
    echo -e "-h, --help        ${Yellow}show brief help${NC}"
    echo -e "-r, --remotes     ${Yellow}select from just remote branches (will fetch first)${NC}"
    echo -e "-a, --all         ${Yellow}select from local and remote branches (will fetch first)${NC}"
    echo -e "-t, --track       ${Yellow}track selected branch${NC}"
    echo -e "-g, --tags        ${Yellow}tag to checkout${NC}"
    echo -e "-b, --rainbow        ${Yellow}RAINBOW OUTPUT MODE${NC}"
    die 0
}


PATTERN="$1"
test -z $PATTERN && print_help
GIT_BRANCH_ACTIONS="--list"
GIT_CHECKOUT_ACTIONS=""
GIT_REF="branch"
RAINBOW_OUTPUT=false;
DEBUG=false;
while test $# -gt 0; do
  case "$1" in
    -h|--help)
      print_help
      ;;
    -d|--debug)
      DEBUG=true;
      shift
      ;;
    -a|--all)
      fetchForRemotes "All branches"
      GIT_BRANCH_ACTIONS="${GIT_BRANCH_ACTIONS} --all"
      shift
      ;;
  	-r|--remotes)
      fetchForRemotes "Remote branches"
      GIT_BRANCH_ACTIONS="${GIT_BRANCH_ACTIONS} --remotes"
      shift
      ;;
  	-t|--track)
      GIT_CHECKOUT_ACTIONS=" --track"
      shift
      ;;
    -b|--rainbow)
      RAINBOW_OUTPUT=true;
      shift
      ;;
    -g|--tags)
      fetchForRemotes "Tags"
      GIT_REF="tag"
      shift
      ;;
    -tr|-rt)
      fetchForRemotes "Remote branches"
      GIT_BRANCH_ACTIONS="${GIT_BRANCH_ACTIONS} --remotes"
      GIT_CHECKOUT_ACTIONS=" --track"
      shift
      ;;
    *)
	  shift
      continue
      ;;
  esac
done

$DEBUG && echo "Debug output"
$DEBUG && echo "Finding branches that match the pattern: $PATTERN"
title "Finding branches matching the pattern \"${PATTERN}\""
MATCHING_BRANCH=$(git $GIT_REF $GIT_BRANCH_ACTIONS | grep -i $PATTERN | sed -E 's/\* (\(HEAD detached at )?//g' )
BRANCHES=($MATCHING_BRANCH)
MATCHCOUNT="${#BRANCHES[@]}"
$DEBUG && echo "Match count: $MATCHCOUNT"

test $MATCHCOUNT -eq 0 && die 1 "${Red}No matching ${GIT_REF} in the repository ${NC}\"$(basename `git rev-parse --show-toplevel`)\"${Red}  ${NC}\"${PATTERN}\"${Red} Exiting...${NC}"

if (($MATCHCOUNT > 1)); then
	title "More than one match. Select the one you want. E.g. type \"1\" to checkout the first item in the list:"

  formatBranches $RAINBOW_OUTPUT "${BRANCHES[@]}"

	echo ""
	re="^[0-9]+$"
	read -p "Enter number {1-$MATCHCOUNT}: " SELECTED_NUMBER
	echo -e "Value read in: \"$SELECTED_NUMBER\""
	if ! [[ $SELECTED_NUMBER =~ $re ]]; then
		  die 1 "${Red}Not a valid option. Exiting...${NC}"
	fi
  if (( $SELECTED_NUMBER < 1 || $SELECTED_NUMBER > $MATCHCOUNT)); then
      die 1 "\"$SELECTED_NUMBER\" ${Red}is of bounds. exiting...${NC}"
  fi
	MATCHING_BRANCH=${BRANCHES[$((--SELECTED_NUMBER))]}
	echo -e "${Yellow}The selected ${GIT_REF} is:${NC} \"$MATCHING_BRANCH\""
fi

title "Checking out ${NC}${MATCHING_BRANCH}"
if $DEBUG; then
  GIT_TRACE=1 git checkout$GIT_CHECKOUT_ACTIONS $MATCHING_BRANCH
else
  git checkout$GIT_CHECKOUT_ACTIONS $MATCHING_BRANCH
fi