#!/bin/sh

FILE_BASHRC="~/.bash/.bash_core/.bashrc.${HOSTNAME}"
FILE_BASH_PROFILE="~/.bash/.bash_core/.bash_profile.${HOSTNAME}"
FILE_GIT_CONFIG="~/.bash/.bash_core/.gitconfig.${HOSTNAME}"

if [ ! -f "$FILE_BASHRC" ]{
	touch "$FILE_BASHRC"
}

if [ ! -f "$FILE_GIT_CONFIG" ]{
	touch "$FILE_GIT_CONFIG"
}

if [ ! -f "$FILE_BASH_PROFILE" ]{
	touch "$FILE_BASH_PROFILE"
}

BASH_BIN_HOSTNAME_FOLDER=~/.bash/${HOSTNAME}
if [ ! -d $BASH_BIN_HOSTNAME_FOLDER ]; then
	mkdir $BASH_BIN_HOSTNAME_FOLDER
fi

FOLDER_SOURCEABLE=${BASH_BIN_HOSTNAME_FOLDER}/sourceable
if [ ! -d $FOLDER_SOURCEABLE ]; then
	mkdir $FOLDER_SOURCEABLE
fi

FOLDER_SCRIPTS=${BASH_BIN_HOSTNAME_FOLDER}/scripts
if [ ! -d $FOLDER_SCRIPTS ]; then
	mkdir $FOLDER_SCRIPTS
fi

FILE_ALIASES=${FOLDER_SOURCEABLE}/aliases
if [ ! -f "$FILE_ALIASES" ]{
	touch "$FILE_ALIASES"
}
