#!/bin/bash

touch ~/.bash/.bash_core/.bashrc.${HOSTNAME}
touch ~/.bash/.bash_core/.bash_profile.${HOSTNAME}
touch ~/.bash/.bash_core/.gitconfig.${HOSTNAME}

BASH_BIN_HOSTNAME_FOLDER=~/.bash/${HOSTNAME}
if [ ! -d $BASH_BIN_HOSTNAME_FOLDER ]; then
	mkdir $BASH_BIN_HOSTNAME_FOLDER
fi

FOLDER_SOURCEABLE=${BASH_BIN_HOSTNAME_FOLDER}/sourceable
if [ ! -d $FOLDER_SOURCEABLE ]; then
	mkdir $FOLDER_SOURCEABLE
fi

FOLDER_SCRIPTS=${BASH_BIN_HOSTNAME_FOLDER}/scripts
if [ ! -d $FOLDER_SCRIPTS ]; then
	mkdir $FOLDER_SCRIPTS
fi

FILE_ALIASES=${FOLDER_SOURCEABLE}/aliases
if [ ! -f "$FILE_ALIASES" ]; then
	touch "$FILE_ALIASES"
fi
