#!/bin/bash

function git_init_full(){
	read -p "Are you sure you want to create a new repository here? (Y|y)"

	if [[ $REPLY =~ [yY] ]]; then
		git init 
		git add .
		git commit 'commit message'
		read -p "Please enter the url for the remote"
		git remote add origin $REPLY
		git push --set-upstream origin master
	fi
}

