#!/bin/bash

function install-epro(){
	cd /C/Dev || die 1 "No /C/Dev folder!"
	git clone git@github.com:BluewireTechnologies/tickets-website.git;
	git clone git@github.com:BluewireTechnologies/epro-ocr.git;
	git clone git@github.com:BluewireTechnologies/epro-filedrop.git;
	git clone git@github.com:BluewireTechnologies/speech-recognition.git;
	git clone git@github.com:BluewireTechnologies/epro.com.git;
	git clone git@github.com:BluewireTechnologies/bluewire-xwiki.git;
}