#!/bin/bash
# 
# Nuget pack wrapper. 
#
# Prerequisites:
# You must either define LOCAL_PACKAGE_STORE here or globally in your env file.
# You must install nuget for command line


say() {
    echo "$@" >&1
}
 
die() {
    say "$2"
    exit "$1"
}

if [[ $1 = "" || $1 = "-h" || $1 = "help" ]]; then
	die 2 "Please supply any number of project directories to pack. E.g. \"C:\Dev\MyRepo\MyProject.csproj\""
	return
fi

if [[ ! -d  "$local_package_store" ]]; then
	say "No local package store. Creating one at $local_package_store"
	mkdir "$local_package_store" 
fi

cd $local_package_store
for ARG in "$@"
do
	echo "Packing $ARG"
    nuget pack $ARG
done 
cd -