#!/bin/sh

BASH_CORE_FILES=~/.bash/.bash_core
if [ ! -d $BASH_CORE_FILES ];then
	mkdir $BASH_CORE_FILES
fi

test -f ~/.bash/.bash_core/.bashrc.${HOSTNAME} && cp ~/.bash/.bash_core/.bashrc.${HOSTNAME} ~/.bashrc
test -f ~/.bash/.bash_core/.bash_profile.${HOSTNAME} && cp ~/.bash/.bash_core/.bash_profile.${HOSTNAME} ~/.bash_profile
test -f ~/.bash/.bash_core/.gitconfig.${HOSTNAME} && cp ~/.bash/.bash_core/.gitconfig.${HOSTNAME} ~/.gitconfig