#!/bin/bash

BACKUP_DIR=~/.bash/backup
if [ ! -d $BACKUP_DIR ];then
	mkdir $BACKUP_DIR
fi

test -f ${BACKUP_DIR}/.bashrc.${HOSTNAME} && cp ${BACKUP_DIR}/.bashrc.${HOSTNAME} ~/.bashrc
test -f ${BACKUP_DIR}/.bash_profile.${HOSTNAME} && cp ${BACKUP_DIR}/.bash_profile.${HOSTNAME} ~/.bash_profile
test -f ${BACKUP_DIR}/.gitconfig.${HOSTNAME} && cp ${BACKUP_DIR}/.gitconfig.${HOSTNAME} ~/.gitconfig
