#!/bin/bash
#
# Pack eyegaze and copy nuspec file to Local Packages
#

set -vx

read  -p "Enter your package version number (i.e. 1.0.0.0): " PACKAGE_VERSION
sed -ir 's/\[assembly: AssemblyFileVersion\(1.0.0.0/${PACKAGE_VERSION}/g' "${eyegaze_repository_dir}/Source/SensorySoftware.EyeGaze.Desktop/Properties/AssemblyInfo.cs"