#!bin/sh
#
# Build scripts for epro and epro everything solutions
#

LOGS_PATH=~/logs/dev/epro/
FILE_PATH_BUILD_OUTPUT_EPRO_EVERYTHING=${LOGS_PATH}last_epro_build_all_output.txt
FILE_PATH_BUILD_OUTPUT_EPRO_SPEECH=${LOGS_PATH}last_epro_build_speech_output.txt
FILE_PATH_BUILD_OUTPUT_EPRO_METAPARSER=${LOGS_PATH}last_epro_build_metaparser_output.txt
FILE_PATH_BUILD_OUTPUT_EPRO=${LOGS_PATH}last_epro_build_output.txt

function epro_build() {
	build_vs /c/Dev/epro/Epro.sln $FILE_PATH_BUILD_OUTPUT_EPRO
}

function epro_build_all() {
	build_vs /c/Dev/epro/Everything.sln $FILE_PATH_BUILD_OUTPUT_EPRO_EVERYTHING 
}

function epro_build_metaparser() {
	build_vs /c/Dev/epro-metaparser/Bluewire.MetaParser.sln $FILE_PATH_BUILD_OUTPUT_EPRO_METAPARSER 
}

function epro_build_speech() {
	build_vs /c/Dev/epro/Bluewire.Speech.sln $FILE_PATH_BUILD_OUTPUT_EPRO_SPEECH 
}

function epro_build_logs() {
	cd LOGS_PATH
}