#!/bin/bash

update-sublime() {
	cd 'C:/Users/bema/AppData/Roaming/Sublime Text 3/Packages/User/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

update-writings() {
	cd 'C:/Users/bema/Documents/Writings/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

