#!/bin/bash

update-sublime() {
	cd 'C:/Users/bema/AppData/Roaming/Sublime Text 3/Packages/User/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

update-writings() {
	cd 'C:/Users/bema/Documents/Writings/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

update-javascript-playground() {
	cd 'C:/Users/bema/Documents/JavaScript/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

epro-update() {
	EPRO_WORKING_DIR=/C/Dev/Epro
	CURRENT_WORKING_DIR=$(pwd)
	if [ "$CURRENT_WORKING_DIR" != "$EPRO_WORKING_DIR" ];
	then
		echo 'Changing directories...'; cd '/C/Dev/Epro' 
	fi

	BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
	echo "Current branch: $BRANCH"
	if [ "$BRANCH" != "master" ];
	then
		echo 'Checking out master...'; git checkout master
	fi

	IS_UP_TO_DATE=$(git status | grep "Your branch is up-to-date with 'origin/master'.")

	if [ -z "$IS_UP_TO_DATE" ];
	then
		git pull
	else
		echo "Your branch is up-to-date with 'origin/master'."
	fi

	if [ "$BRANCH" != "master" ];
	then
		echo 'Checking out previous branch...'; git checkout -
	fi

	if [ "$CURRENT_WORKING_DIR" != "$EPRO_WORKING_DIR" ];
	then
		echo 'Returning to previous directory...'; cd -
	fi
	return
 }
