#!/bin/bash
BIN_COPY_PATH=/C/Dev/tools/scripts/bash/scripts/
SOURCEABLE_COPY_PATH=/C/Dev/tools/scripts/bash/sourceable/
cp ~/.bash/global/scripts/git/git-log-release $BIN_COPY_PATH
cp ~/.bash/global/scripts/git/glogu ${BIN_COPY_PATH}/git-unique-log
sed --in-place "s_glogu_git-unique-log_g" ${BIN_COPY_PATH}/git-unique-log
cp ~/.bash/global/scripts/git/gchu ${BIN_COPY_PATH}/git-unique-checkout
sed --in-place "s_gchu_git-unique-checkout_g" ${BIN_COPY_PATH}/git-unique-checkout
cp ~/.bash/global/scripts/git/griu ${BIN_COPY_PATH}/git-unique-rebase
sed --in-place "s_griu_git-unique-rebase_g" ${BIN_COPY_PATH}/git-unique-rebase
cp ~/.bash/global/scripts/nuget-pack $BIN_COPY_PATH
cp ~/.bash/global/scripts/msbuild32 $BIN_COPY_PATH
cp ~/.bash/global/scripts/git/format-branches $BIN_COPY_PATH

cp -r ~/.bash/BAN-WORK-TOP/scripts/application/pack/* /C/Dev/tools/scripts/bash/scripts/
cp -r ~/.bash/BAN-WORK-TOP/scripts/application/build/* /C/Dev/tools/scripts/bash/scripts/
cp -r ~/.bash/BAN-WORK-TOP/scripts/git-tag-release /C/Dev/tools/scripts/bash/scripts/
