#!/bin/bash

dt=$(date '+%d-%m-%Y_%H-%M-%S');

rm -fr '/c/temp/Development builds/devbuild'

cp -r "${grid_repository_dir}/Source/SensorySoftware.Grids.Grid3.Desktop/bin/x86/Debug/net45" '/c/temp/Development builds'

mv '/c/temp/Development builds/net45' '/c/temp/Development builds/devbuild' # future if you want to preserve the name-'$dt

echo $dt > '/c/temp/Development builds/devbuild/build_info.txt'

