#!/bin/bash
update-magic() {
	cdmagic
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

update-sublime() {
	cd 'C:/Users/BAN/AppData/Roaming/Sublime Text 3/Packages/User/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

update-writings() {
	cd 'C:/Users/BAN/Documents/Writings/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}

update-python() {
	cd 'C:/Users/BAN/Documents/Python/'
	git pull
	git add .
	git commit -m'generic update'
	git push
	cd -
	ascii_ok
	return
}
