#!/bin/bash

RAINBOW_OUTPUT=$1
shift
BRANCHES=("$@")
i=1
MAX_LENGTH=0;
Blue='\033[0;34m'
Yellow='\033[0;33m'
On_Blue='\033[44m'
Red='\033[0;31m'
Green='\033[0;32m'
UWhite='\033[0;37m'

for BRANCH in ${BRANCHES[@]}; do
  BRANCH_LENGTH=$(expr length $BRANCH)
  if (( BRANCH_LENGTH > MAX_LENGTH )); then
    MAX_LENGTH=$BRANCH_LENGTH
  fi
done
for BRANCH in ${BRANCHES[@]}; do
  if $RAINBOW_OUTPUT; then
    let OPTION=$((i++))
    echo -e "\e[3$(( $RANDOM * 6 / 32767 + 1 ))m$(printf %6s $OPTION) => $BRANCH"
  else
    let OPTION=$((i++))
    BRANCH_LENGTH=$(expr length $BRANCH)
    LENGTH_DIFF=$((MAX_LENGTH-BRANCH_LENGTH))
    echo -e " ${UWhite}$(printf %3s $OPTION) => ${Yellow}$BRANCH$(printf %${LENGTH_DIFF}s)   ${NC}"
  fi
done
