#!/bin/bash

git log --color --graph --all --abbrev-commit --oneline --pretty=tformat:'%C(auto)%h -%d%Creset %C(bold green)<%an>%C(auto) %C(bold blue)%cr %C(reset)%C(yellow)%s %b' | grep "<Bernard Mason>" | head -n "$1"