#!/bin/bash
# basic interactive rebase script (grem)
# Assumes that your target default branch is "main" or "master"
# If neither exists, it will throw an error and exit

echo "grem: interactive rebase script"

function die() {
    local exit_code=$1
    shift
    echo -e "${RED}$@${NC}" >&2
    exit $exit_code
}

UPDATE_DEFAULT_BRANCH=false
if [ "$1" == "-u" ]; then
    UPDATE_DEFAULT_BRANCH=true
    shift
fi

# First check if we are in a git repository
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    echo "Not in a git repository. Exiting."
    exit 1
fi

# Check if there are any uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo "There are uncommitted changes. Please commit or stash them before running this script."
    exit 1
fi

# Discover the default branch
default_branch=$(git branch --list "main" "master" | head -n 1 | sed 's/^[* ] //')
if [ -z "$default_branch" ]; then
    die 1 "Error: No branches found in the repository."
fi
# Check if both branches exists and give an option to the user on which one to use
if git show-ref --verify --quiet refs/heads/main && git show-ref --verify --quiet refs/heads/master; then
    echo "Both main and master branches exist. Which one do you want to use?"
    select branch in "main" "master"; do
        case $branch in
            main ) default_branch="main"; break;;
            master ) default_branch="master"; break;;
            * ) echo "Invalid option. Please try again.";;
        esac
    done
fi

# if current branch is the default branch then exit
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" == "$default_branch" ]; then
    die 1 "Error: Do not rebase the default branch ($default_branch) onto itself."
fi

# Check for upstream updates to the default branch
if $UPDATE_DEFAULT_BRANCH; then
    current_branch=$(git rev-parse --abbrev-ref HEAD)
    git pull origin "$default_branch"
    if [ $? -ne 0 ]; then
        die 1 "Error: Unable to pull updates for $default_branch."
    fi
fi

git rebase -i "$default_branch"


