#!/bin/bash

# Bernie help pages
alias bhelp='vim ~/.bash/global/bhelp/bhelp'
alias bashi='bash -c "help set"'

# Directory alias (computer specific)
alias cdd='cd ~/Documents/'
alias cdw='cd ~/Documents/Writings/'
alias cd..='cd ..'
alias cdb='cd ~/.bash'
alias xh="explorer ."

# find alias list
alias fn='find -name'
alias ffn='find -type f -name'

# grep alias
alias gxr='grep -rn --color=always'

# application
alias vscode='code .'

# VS
alias vsdevcmd="/C/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Professional/Common7/Tools/VsDevCmd.bat"

# text comparison alias list
alias dif='diff -u'

# bash aliases 
alias edit-bash-aliases="vim ~/.bash/global/aliases"
alias edit-bash-aliases-local="vim ~/.bash/${HOSTNAME}/aliases"
alias edit-bash-config="vim ~/.bash/global/config"
alias edit-bash-config-local="vim ~/.bash/${HOSTNAME}/config"
alias edit-bash-env="vim ~/.bash/global/env"
alias edit-bash-scripts="vim ~/.bash/global/scripts"
alias edit-bash-scripts-local="vim ~/.bash/${HOSTNAME}/Scripts/update-scripts"
alias edit-bashrc="vim ~/.bashrc"
alias edit-bash-profile=" vim ~/.bash_profile"
alias view-bash-aliases="cat ~/.bash/global/aliases; cat ~/.bash/${HOSTNAME}/aliases"
alias view-bash-config="cat ~/.bash/global/config; cat ~/.bash/l/${HOSTNAME}/config"
alias view-bash-scripts="cat ~/.bash/global/scripts; cat ~/.bash/${HOSTNAME}/scripts"

# Debugging aliases
alias debug="#set -o nounset; set -o xtrace"

# Git alias list
alias ga='git add'
alias gaa='git add .'
alias garo='git add remote origin'
alias gc='git commit'
alias gca='git commit --amend'
alias gcaa='git commit --amend -a'
alias gcaan='git commit --amend -a --no-edit'
alias gcl='git clean -fd'
alias gd='git diff'
alias gpfwl='git push --force-with-lease'
alias gpus='git push'
alias gpusom='git push -u origin master'
alias gphead='git push -u origin HEAD'
alias gpul='git pull'
alias gpulv='GIT_CURL_VERBOSE=1 GIT_TRACE=1 git pull'
alias gs='git status -u'
alias gr='git remote'
alias gri='git remote -v'
alias grem='git rebase -i master'
alias grec='git rebase --continue'
alias grea='git rebase --abort'
alias gitkba='gitk --all --remotes &'
alias gitkb='gitk &'
alias gclx='git clean -fxd -e "*.vscode"'
alias grpu='git rev-parse --abbrev-ref --symbolic-full-name HEAD@{upstream}'
alias ggc='git fsck && git gc --prune=now'

## Git logging alias
alias glod='git log --oneline --decorate'
alias glodg='git log --oneline --decorate --graph'
alias glodga='git log --oneline --decorate --graph --all'

## Git branching alias
alias gb='git branch'
alias gfb='git branch -a | grep '
alias gbi='git branch -vv'
alias gch='git checkout'
alias gchh='git checkout .'
alias gchp='git checkout -'
alias gchb='git checkout -b'
alias gchm='git checkout master'
alias grbi='git remote -v show origin'
alias gst='git stash'
alias gstp='git stash pop'

# Package managers
alias npm-update='npm install -g npm'

# random other alias
# alias ROT13='tr a-zA-Z n-za-mN-ZA-M'

#-------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls).
#-------------------------------------------------------------
# Add colors for filetype and  human-readable sizes by default on 'ls':
alias ls='ls -h --color'
alias lx='ls -lXB'         #  Sort by extension.
alias lk='ls -lSr'         #  Sort by size, biggest last.
alias lt='ls -ltr'         #  Sort by date, most recent last.
alias lc='ls -ltcr'        #  Sort by/show change time,most recent last.
alias lu='ls -ltur'        #  Sort by/show access time,most recent last.
alias lh='ls .* --color=auto'
alias ll='ls -ls --color=auto'
alias l.='ls -la --color=auto'
alias lbhelp='cd ~/.bash/bhelp; ls | grep .; cd ~'


# powershell
alias pstos='powershell turn-off-screen'