#!/bin/bash

# Bernie help pages
alias bhelp='vim ~/.bash/global/bhelp/bhelp'
alias bashi='bash -c "help set"'

# General bash
alias reloadbash='source ~/.bash_profile'

# Directory alias (computer specific)
alias cdd='cd ~/Documents/'
alias cdw='cd ~/Documents/Writings/'
alias cd..='cd ..'
alias cdb='cd ~/.bash'
alias xh="explorer ."

# find alias list
alias fn='find -name'
alias ffn='find -type f -name'

# grep alias
alias gxr='grep -rn --color=always'

# application
alias vscode='code .'

# VS
alias vsdevcmd="/C/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Professional/Common7/Tools/VsDevCmd.bat"

# text comparison alias list
alias dif='diff -u'

# XML lintiing
alias xmllint='xmllint --noout'

# nuget
alias nuget-locals='nuget locals all -list'
alias nuget-clear-all-caches='nuget locals all -clear'
alias nuget-sources='nuget sources list'
alias edit-global-nuget='vim ~/AppData/Roaming/NuGet/NuGet.config'

# bash aliases 
alias edit-bash-aliases="vim ~/.bash/global/sourceable/aliases"
alias edit-bash-aliases-local="vim ~/.bash/${HOSTNAME}/sourceable/aliases"
alias edit-bash-config="vim ~/.bash/global/config"
alias edit-bash-config-local="vim ~/.bash/${HOSTNAME}/config"
alias edit-bash-env="vim ~/.bash/global/env"
alias edit-bash-scripts="vim ~/.bash/global/scripts"
alias edit-bash-scripts-local="vim ~/.bash/${HOSTNAME}/Scripts/update-scripts"
alias edit-bashrc="vim ~/.bashrc"
alias edit-bash-profile=" vim ~/.bash_profile"
alias view-bash-aliases="cat ~/.bash/global/sourceable/aliases; cat ~/.bash/${HOSTNAME}/sourceable/aliases"
alias view-bash-config="cat ~/.bash/global/config; cat ~/.bash/l/${HOSTNAME}/config"
alias view-bash-scripts="cat ~/.bash/global/scripts; cat ~/.bash/${HOSTNAME}/scripts"
alias tmux-help="cat ~/.bash/bhelp/tmux"

# Debugging aliases
alias debug="#set -o nounset; set -o xtrace"

# Git alias list
alias ga='git add'
alias gaa='git add .'
alias gap='git add --patch'
alias garo='git add remote origin'
alias gb='git branch'
alias gbm='git branch --merged'
alias gbmm='git branch --merged master'
alias gbr='git branch --remotes'
alias gc='git commit'
alias gca='git commit --amend'
alias gcaa='git commit --amend -a'
alias gcaan='git commit --amend -a --no-edit'
alias gcawip='git add .; git commit -a -m WIP'
alias gcm='git commit -m'
alias gcl='git clean -fd'
alias gcp='git cherry-pick'
alias gcpn='git cherry-pick --no-commit'
alias gpfwl='git push --force-with-lease'
alias gpus='git push'
alias gpusom='git push -u origin master'
alias gphead='git push -u origin HEAD'
alias gpul='git pull'
alias gpulv='GIT_CURL_VERBOSE=1 GIT_TRACE=1 git pull'
alias gpr='git prune'
alias gpro='git remote prune origin'
alias gs='git status -sbu'
alias gr='git reset'
alias grp='git reset --patch'
alias grem='git remote'
alias gremi='git remote -v'
alias grepo='git remote prune origin'
alias grem='git rebase -i origin/master'
alias grefm='git fetch && git rebase -i origin/master'
alias grec='git rebase --continue'
alias grea='git rebase --abort'
alias gitkba='gitk --all --remotes &'
alias gitkb='gitk &'
alias gclx='git clean -fxd -e "*.vscode"'
alias grpu='git rev-parse --abbrev-ref --symbolic-full-name HEAD@{upstream}'
alias ggc='git fsck && git gc --prune=now'

## Git diffing
alias gd='git diff'
alias gdc='git diff --cached'
alias gdn='git diff --no-index /dev/null'
alias gdw='git diff --word-diff=color'
alias gdmin='git diff --word-diff=color -U0'
alias gdf='git diff --name-only'
alias gdfm='git diff --name-only master..HEAD'

# show and blame
alias gsh='git show -w'
alias gshw='git show -w --word-diff=color'
alias gshmin='git show -w --word-diff=color -U0'
alias gbl='git blame -c'

## Git logging alias
alias glom='git log --oneline master..HEAD'
alias glod='git log --oneline --decorate'
alias glodg='git log --oneline --decorate --graph'
alias glodga='git log --oneline --decorate --graph --all'

## Git branching alias
alias gb='git branch'
alias gfb='git branch -a | grep '
alias gbi='git branch -vv'
alias gch='git checkout'
alias gchh='git checkout .'
alias gchp='git checkout -'
alias gchb='git checkout -b'
alias gcht='git checkout --track' # provide origin/branchname to create branchname
alias gchm='git checkout master'
alias gchr='git rev-parse --abbrev-ref --symbolic-full-name HEAD@{upstream} | xargs git checkout'
alias grbi='git remote -v show origin'
alias gst='git stash'
alias gstp='git stash pop'

# tmux aliases
alias tma='tmux attach'
alias tmas='tmux attach-session -t'
alias tmls='tmux list-sessions'
alias tmd='tmux detach'

# Package managers
alias npm-update='npm install -g npm'

# random other alias
# alias ROT13='tr a-zA-Z n-za-mN-ZA-M'

#-------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls).
#-------------------------------------------------------------
# Add colors for filetype and  human-readable sizes by default on 'ls':
alias ls='ls -h --color'
alias lx='ls -lXB'         #  Sort by extension.
alias lk='ls -lSr'         #  Sort by size, biggest last.
alias lt='ls -ltr'         #  Sort by date, most recent last.
alias lc='ls -ltcr'        #  Sort by/show change time,most recent last.
alias lu='ls -ltur'        #  Sort by/show access time,most recent last.
alias lh='ls .* --color=auto'
alias ll='ls -ls --color=auto'
alias l.='ls -la --color=auto'

# disk usage
alias du1='du -h -d 1'
alias du2='du -h -d 2'

# List of help topics
alias lbhelp='cd ~/.bash/bhelp; ls | grep .; cd ~'

# powershell
alias pstos='powershell turn-off-screen'

# Windows
alias kill-msbuild='taskkill //IM msbuild.exe //F'	
# Workaround for python on windows: https://stackoverflow.com/questions/32597209/python-not-working-in-the-command-line-of-git-bash
alias python='winpty python.exe'