#!/bin/bash

function git-init-full(){
	read -p "Are you sure you want to create a new repository here? (Y|y)"

	if [[ $REPLY =~ [yY] ]]; then
		git init 
		git add .
		git commit 'commit message'
		read -p "Please enter the url for the remote"
		git remote add origin $REPLY
		git push --set-upstream origin master
	fi
}

function git-generic-update(){
	cd "$1" || die 1 "Directory doesn't exist"

	local ISUPTODATE=$(git status | grep "Your branch is up-to-date with \'origin/master\'.")
	if [ -z "$ISUPTODATE" ];
	then
		git pull || die 1 "Couldn't pull"
	else
		echo "Y'all already up-to-date."
	fi
	local ISWORKINGTREECLEAN=$(git status | grep "nothing to commit, working tree clean")
	if [ -z "$ISWORKINGTREECLEAN" ];
	then
		git add .
		git commit -m 'Generic update'
		git push || die 1 "Couldn't push"
	else
		echo "Nothing to commit yo, working tree clean."
	fi
	cd -
}